# Generated by Django 2.1.7 on 2019-03-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MalwareSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileHash', models.CharField(max_length=256)),
                ('filePath', models.CharField(max_length=256)),
                ('file', models.FileField(upload_to='tmp/')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
