# Generated by Django 2.2 on 2019-04-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MalwareSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileHash', models.CharField(max_length=256)),
                ('filePath', models.CharField(max_length=256)),
                ('fileBlob', models.FileField(upload_to='samples/')),
                ('date', models.DateField(auto_now=True)),
                ('ready', models.BooleanField(default=False)),
                ('file', models.CharField(max_length=2560)),
                ('readelf', models.CharField(max_length=2560)),
                ('objdump', models.CharField(max_length=2560)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicTitle', models.CharField(max_length=256)),
                ('topicBody', models.CharField(max_length=2560)),
            ],
        ),
    ]
