# Generated by Django 2.2 on 2019-04-10 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='malwaresample',
            name='filePath',
        ),
        migrations.AlterField(
            model_name='malwaresample',
            name='fileBlob',
            field=models.FileField(upload_to=''),
        ),
    ]
