# Generated by Django 2.2.1 on 2019-05-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malwaresample',
            name='objdump',
            field=models.CharField(max_length=2560000),
        ),
        migrations.AlterField(
            model_name='malwaresample',
            name='readelf',
            field=models.CharField(max_length=2560000),
        ),
    ]
