#adapted from example in docker documentation
version: '3'

services:
  web:
    build: .
    volumes:
      - .:/code
    #ports:
    #  - 8000:8000
    expose:
      - 8000
    environment:
      - DEBUG=1
      - SECRET_KEY=${SEC_KEY}
    restart: always
    depends_on:
      - "redis"
    command: python /code/wikivir/manage.py runserver 0.0.0.0:8000

  redis:
    restart: always
    image: redis
    expose:
      - "6379"
    #ports:
    #  - 6379:6379
    #volumes:
    #  - redisdata:/data
  
  nginx:
    restart: always
    build: ./nginx/
    depends_on:
      - web
    ports:
            - "80:80"
            #- "8000:8000"
    links:
      - web:web



