#adapted from example in docker documentation
version: '3'

services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - "redis"
    command: python /code/wikivir/manage.py runserver 0.0.0.0:8000

  redis:
    restart: always
    image: redis
    expose:
      - "6379"
    #ports:
    #  - 6379:6379
    #volumes:
    #  - redisdata:/data



